### ISSUE TITLE
Issue with JupyterLab Extensions and nbgitpuller Installation

### ISSUE THREAD

**Issue by mantrakp04** [UBC-STAT/stat-201#8]
Hello,

I am encountering an issue during the installation process involving multiple components, including nbgitpuller and various JupyterLab extensions. The process fails at a specific point in the [Dockerfile](https://github.com/UBC-STAT/stat-201/blob/9427396c1f5f7e7b31c2c0fae24e7be5c1ddc34d/dockerfiles/r-stat-201/Dockerfile#L38-L43), detailed below:

```docker
RUN pip install git+https://github.com/data-8/nbgitpuller@c23461d4f7ce47ec4e0d2bcfc3b2fde4939b80f8 \
  && jupyter serverextension enable --sys-prefix nbgitpuller \
  && pip install jupyterlab-git \
  && pip install jupytext --upgrade \
  && jupyter labextension install @techrah/text-shortcuts \
  && jupyter lab build
```

To troubleshoot, I experimented with modifying the command syntax. I changed `jupyter serverextension enable --sys-prefix nbgitpuller` to `jupyter server extension enable --sys-prefix nbgitpuller`. This adjustment did not resolve the issue.

The failure consistently occurs at this line: `jupyter labextension install @techrah/text-shortcuts`. I attempted a similar syntax modification here, changing `labextension` to `lab extension`, but this led to the command failing at the modified `jupyter lab extension install @techrah/text-shortcuts`.

Unfortunately, I haven't been able to find a solution or workaround for this problem. Any assistance or suggestions would be greatly appreciated.

Thank you for the help.

**Comment by briank-git** [comment]
Fixed by #9
